### ISSUE TITLE
不存在tmp\verifycode.jpg

### ISSUE THREAD

**Issue by hueidou** [xhan/qqbot#34]
如下提示，我手动创建对应文件后正常。

	[Sat Apr 25 2015 21:30:37 GMT+0800 (中国标准时间)] INFO 登录 step0 验证码检测
	[Sat Apr 25 2015 21:30:38 GMT+0800 (中国标准时间)] INFO 登录 step0.5 获取验证码
	[Sat Apr 25 2015 21:30:38 GMT+0800 (中国标准时间)] ERROR Error: ENOENT, no such
	file or directory 'c:\Users\fakepath\node_modules\hubot-qq\tmp\verifycode.jpg'

	  at Object.fs.openSync (fs.js:427:18)
	  at Object.fs.writeFileSync (fs.js:966:15)
	  at create_img_server (c:\Users\fakepath\node_modules\hubot-qq\src\qqauth.cof
	fee:80:3, <js>:101:8)
	  at IncomingMessage.<anonymous> (c:\Users\fakepath\node_modules\hubot-qq\src\
	qqauth.coffee:64:7, <js>:79:9)
	  at IncomingMessage.EventEmitter.emit (events.js:117:20)
	  at _stream_readable.js:919:16
	  at process._tickCallback (node.js:419:13)

另外，验证码一直出错。

	[Sat Apr 25 2015 21:37:38 GMT+0800 (中国标准时间)] INFO 登录 step0 验证码检测
	[Sat Apr 25 2015 21:37:39 GMT+0800 (中国标准时间)] INFO 登录 step0.5 获取验证码
	[Sat Apr 25 2015 21:37:39 GMT+0800 (中国标准时间)] NOTICE 打开该地址-> http://lo
	calhost:12345
	输入验证码:LMZM
	[Sat Apr 25 2015 21:37:49 GMT+0800 (中国标准时间)] NOTICE 验证码： LMZM
	[Sat Apr 25 2015 21:37:49 GMT+0800 (中国标准时间)] INFO 登录 step1 密码校验
	[Sat Apr 25 2015 21:37:49 GMT+0800 (中国标准时间)] ERROR 登录 step1 failed [ '4'
	, '0', '', '0', '您输入的验证码不正确，请重新输入。', 'fakenumber' ]

**Comment by masahoshiro** [comment]
作者貌似在修

**Comment by sunqi0928** [comment]
验证码的问题应该一样： https://github.com/xhan/qqbot/issues/40

**Comment by kinosang** [comment]
@sunqi0928 请确认你所使用的版本是最新版，上次更新是 7/8， pull request #36
