### ISSUE TITLE
hubot下登陆成功，update_group_member报错

### ISSUE THREAD

**Issue by hueidou** [xhan/qqbot#38]
奇怪的是单独用qqbot不报这个错误。

	[Fri Jul 10 2015 15:01:20 GMT+0800 (CST)] INFO 登录 step0 验证码检测
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] INFO - 无需验证码
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] INFO 登录 step1 密码校验
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] INFO 登录 step2 cookie获取
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] DEBUG response: 302
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] INFO 登录 step3 token 获取
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] DEBUG login token response: 200
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] INFO 登录成功 
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] DEBUG Loading Plugin help
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] INFO fetching group list
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] INFO √ group list fetched
	[Fri Jul 10 2015 15:01:21 GMT+0800 (CST)] INFO fetching groupmember 
	[Fri Jul 10 2015 15:01:22 GMT+0800 (CST)] ERROR TypeError: Cannot read property
	'code' of undefined
	  at QQBot.update_group_member (/home/san/totoro/node_modules/hubot-qq/src/qqbot
	.coffee:106:5, <js>:149:45)
	  at /home/san/totoro/node_modules/hubot-qq/src/qqbot.coffee:471:7, <js>:638:22
	  at /home/san/totoro/node_modules/hubot-qq/src/qqbot.coffee:92:9, <js>:128:18
	  at /home/san/totoro/node_modules/hubot-qq/src/qqapi.coffee:182:5, <js>:206:16
	  at handle_resp_body (/home/san/totoro/node_modules/hubot-qq/src/httpclient.cof
	fee:69:5, <js>:77:12)
	  at IncomingMessage.<anonymous> (/home/san/totoro/node_modules/hubot-qq/src/htt
	pclient.coffee:51:9, <js>:53:16)
	  at IncomingMessage.emit (events.js:129:20)
	  at _stream_readable.js:908:16
	  at process._tickCallback (node.js:355:11)

	[Fri Jul 10 2015 15:01:22 GMT+0800 (CST)] INFO √ buddy list fetched

**Comment by npk48** [comment]
我也遇到了这个问题 貌似是群名片获取的协议有误 qqapi.coffee:182:5

**Comment by elprup** [comment]
遇到这种情况的一种可能是创建了“群聊”而不是“群”。
