### ISSUE TITLE
无法运行呀~！，求指导

### ISSUE THREAD

**Issue by danwey** [xhan/qqbot#46]
[Tue May 17 2016 12:22:15 GMT+0900 (JST)] INFO 登录 step2 cookie获取
[Tue May 17 2016 12:22:15 GMT+0900 (JST)] INFO 登录 step3 token 获取
[Tue May 17 2016 12:22:15 GMT+0900 (JST)] DEBUG login token response: 403

undefined:1
<html><body><h1>403 Forbidden</h1>
^
SyntaxError: Unexpected token <
  at Object.parse (native)
  at IncomingMessage.<anonymous> (/root/code/qqbot/src/qqauth_qrcode.js:215:20)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:448:13)

**Comment by jinchan-ck** [comment]
+1

**Comment by oscarqht** [comment]
+1

**Comment by blambin** [comment]
https://github.com/floatinghotpot/qqbot 你们试下这个分支行不行，也很久没更新了

**Comment by plutoid** [comment]
用普通用户运行, 否则试试:
chmod g+w /root
